# Generated by Django 3.2.18 on 2023-06-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_deliveryservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
