# Generated by Django 3.2.18 on 2023-06-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_product_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyer_id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_contact', models.CharField(max_length=50)),
                ('buyer_date_of_birth', models.DateField(null=True)),
                ('buyer_sex', models.CharField(blank=True, max_length=50)),
                ('buyer_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='date_of_birth',
            new_name='farmer_date_of_birth',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='password',
            new_name='farmer_password',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='sex',
            new_name='farmer_sex',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.buyer'),
        ),
    ]
