# Generated by Django 3.2.18 on 2023-06-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmer_id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=100)),
                ('farmer_contact', models.CharField(max_length=50)),
                ('farmer_location', models.CharField(max_length=50)),
                ('product_grown', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('sex', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
