# Generated by Django 3.2.18 on 2023-06-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('deliveryservice_id', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryservice_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
            ],
        ),
    ]
